### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!

### ISSUE THREAD

**Issue by codypl** [dantheman213/spotify-playlist-to-json#3]
After sending the query, I was looking for result but the status stays to "downloading".
And in Docker I saw this error "UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!", here is the logs :

```
spotify-playlist-to-json_1 | Task started at 2/18/2021, 9:18:43 PM

spotify-playlist-to-json_1 | Starting headless browser...

spotify-playlist-to-json_1 | (node:18) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!

spotify-playlist-to-json_1 | /opt/app/node_modules/puppeteer/.local-chromium/linux-706915/chrome-linux/chrome: error while loading shared libraries: libXtst.so.6: cannot open shared object file: No such file or directory

spotify-playlist-to-json_1 |

spotify-playlist-to-json_1 |

spotify-playlist-to-json_1 | TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

spotify-playlist-to-json_1 |

spotify-playlist-to-json_1 | at onClose (/opt/app/node_modules/puppeteer/lib/Launcher.js:348:14)

spotify-playlist-to-json_1 | at Interface.<anonymous> (/opt/app/node_modules/puppeteer/lib/Launcher.js:337:50)

spotify-playlist-to-json_1 | at Interface.emit (events.js:205:15)

spotify-playlist-to-json_1 | at Interface.close (readline.js:401:8)

spotify-playlist-to-json_1 | at Socket.onend (readline.js:178:10)

spotify-playlist-to-json_1 | at Socket.emit (events.js:205:15)

spotify-playlist-to-json_1 | at endReadableNT (_stream_readable.js:1137:12)

spotify-playlist-to-json_1 | at processTicksAndRejections (internal/process/task_queues.js:84:9)

spotify-playlist-to-json_1 | (node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

spotify-playlist-to-json_1 | (node:18) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by marcusdavanco** [comment]
I got the same problem:

![image](https://user-images.githubusercontent.com/4138199/146100027-412e4c0d-f831-45e4-8589-16b83329f805.png)
